// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//
// Load ADT 2
// Test reading complex adts in CSV format
//


.type Nat = S {x : Nat}
          | Zero {}


.decl NumToNat, O(u: unsigned, n: Nat)

.input NumToNat

O(u, n) :- NumToNat(u, n).
.output O
