// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test storing of record with a single level of nesting

.type pair = [ first : number, second : number ]

.decl A(x: pair)
A([1, 2]).
A([1, -1]).
A([3, 3]).
A(nil).

.output A(IO=stdout,headers=true)
