.comp ParserTest {
    .decl declA(u: number)
    .decl functorA(u: number)
    .decl inputA(u: number)
    .decl outputA(u: number)
    .decl printsizeA(u: number)
    .decl limitsizeA(u: number)
    .decl typeA(u: number)
    .decl compA(u: number)
    .decl initA(u: number)
    .decl number_typeA(u: number)
    .decl symbol_typeA(u: number)
    .decl overrideA(u: number)
    .decl pragmaA(u: number)
    .decl planA(u: number)
}

.init pt = ParserTest
pt.declA(3).
pt.functorA(3).
pt.inputA(3).
pt.outputA(3).
pt.printsizeA(3).
pt.limitsizeA(3).
pt.typeA(3).
pt.compA(3).
pt.initA(3).
pt.number_typeA(3).
pt.symbol_typeA(3).
pt.overrideA(3).
pt.pragmaA(3).
pt.planA(3).
