// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//
// Type System 9
//
// Check if subset types work correctly with float/unsigned
//


.type A <: float
.type B <: unsigned


.decl relAB(a: A, b: B)
relAB(1, 1).
relAB(0.5, 0xffffffff).


.output relAB
