// Souffle - A Datalog Compiler
// Copyright (c) 2016, Oracle and/or its affiliates. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Choice test-case (cf. Issue #1905)

.decl b(x: number, y: number) choice-domain x
.decl c(x: number, y: number)
b(x, y) :- c(x, y).
c(2, 0).
c(2, 5).
.output b

.comp Comp {
  .decl b(x: number, y: number) choice-domain x
  .decl c(x: number, y: number)
  b(x, y) :- c(x, y).
}
.init comp = Comp
comp.c(2, 0).
comp.c(2, 5).
.output comp.b
