// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test reading of a simple record.

.type tuple = [f: number, s: number, t: symbol]


.decl A(x: tuple)
.input A()

.decl B(x: tuple)
B(x) :- A(x).

.output B()
