// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test reading of nested records

.type Tree = [ left: Tree, val: number, right: Tree ]


.decl I(t: Tree)
.input I

.decl O(t: Tree)
O(t) :- I(t).

.output O
