name: Package for Ubuntu 20.10 64bit
description: Package for Ubuntu 20.10 64bit
inputs:
  package_cloud_api_key:
    description: 'Package Cloud API Key'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package_cloud_api_key }}