// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test reading of multiple records

.type tuple = [f: number, s: number, t: symbol]


.decl A(x: tuple, y: tuple, z: tuple)
.input A()

.decl B(x: tuple, y: tuple, z: tuple)
B(x, y, z) :- A(x, y, z).

.output B(IO=stdout)
